### ISSUE TITLE
MOV to MP4 convertion

### ISSUE THREAD

**Issue by igorbakman** [hullarb/javacpp-ffmpeg-example#1]
hi,

trying to convert a MOV video to MP4.

The video is contained out of 2 streams:
![image](https://user-images.githubusercontent.com/4776228/56962813-b684e400-6b57-11e9-9bfc-29e0341c42c0.png)

I keep getting "Could not find tag for codec pcm_s16le in stream" 

When I run ffmpeg as an exe file, I do manage to convert.

Have any idea?

**Comment by hullarb** [comment]
Hi,

Did you specify any audio conversion argument to the ffmpeg command line? Because as far as i know pcm_s16be is not supported in mp4 containers. https://ffmpeg.org/pipermail/libav-user/2016-January/008756.html

**Comment by igorbakman** [comment]
I forgot to mention this, but I'm skipping the audio stream, I'm trying to convert only the video stream.

I've edited your code to skip the audio streams

**Comment by hullarb** [comment]
Are you sure you're skipping the creation of the output stream in the output as well? because the error message is specific to the audio stream.

**Comment by igorbakman** [comment]
yes, I'm sure.
This is another MOV file that I'm able to convert, please notice the streams are in a different order
![image](https://user-images.githubusercontent.com/4776228/57221135-45817880-6ffe-11e9-82d8-6b1db2ba0dff.png)

**Comment by hullarb** [comment]
could you share the modified code you use?

**Comment by igorbakman** [comment]
I've just rearranged the code a bit, to make it more readable for myself

[mov2mp4Conveter.zip](https://github.com/hullarb/javacpp-ffmpeg-example/files/3148006/mov2mp4Conveter.zip)

**Comment by igorbakman** [comment]
@hullarb thanks for the help, I found out the problem - I've missed the numbering on one occasion.
